//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebUI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_city
    {
        public string city_cd { get; set; }
        public string city_nam { get; set; }
        public string state_cd { get; set; }
        public string rec_stus { get; set; }
        public System.DateTime crtd_on { get; set; }
    }
}
