//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebUI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_subject
    {
        public int row_id { get; set; }
        public string student_cd { get; set; }
        public string subject_cd { get; set; }
        public string rec_stus { get; set; }
        public System.DateTime crtd_on { get; set; }
    }
}
